<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250826190332 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dataset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, filename VARCHAR(255) NOT NULL, file_type VARCHAR(50) NOT NULL, file_size INT NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, mkt_value NUMERIC(10, 4) DEFAULT NULL, temperature_readings_count INT NOT NULL, min_temperature NUMERIC(8, 4) DEFAULT NULL, max_temperature NUMERIC(8, 4) DEFAULT NULL, avg_temperature NUMERIC(8, 4) DEFAULT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, activation_energy NUMERIC(8, 4) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE temperature_reading (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, temperature NUMERIC(8, 4) NOT NULL, temperature_kelvin NUMERIC(8, 4) DEFAULT NULL, unix_timestamp INT DEFAULT NULL, original_data TEXT DEFAULT NULL, dataset_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C37E1373D47C2D1B ON temperature_reading (dataset_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE temperature_reading ADD CONSTRAINT FK_C37E1373D47C2D1B FOREIGN KEY (dataset_id) REFERENCES dataset (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE temperature_reading DROP CONSTRAINT FK_C37E1373D47C2D1B');
        $this->addSql('DROP TABLE dataset');
        $this->addSql('DROP TABLE temperature_reading');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
